build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%
  - ECHO conda --version

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy scikit-learn nose cython
  - activate test-environment
  - pip install deap
  - pip install xgboost

test_script:
  - nosetests -s -v
  
